canvas=document.getElementById("myCanvas");
ctx= canvas. getContext("2d");
ctx. beginPath();
ctx. strokeStyle = "red";
ctx. lineWidth = 1;
ctx. rect(150, 143, 500, 300);
ctx. stroke();
ctx. beginPath() ;
ctx. strokeStyle = "blue";
ctx. lineWidth = 5;
ctx. arc(315, 265, 40 ,0 , 2 * Math.PI);
ctx. stroke();
ctx. beginPath() ;
ctx. strokeStyle = "black";
ctx. lineWidth = 5;
ctx. arc(405, 265, 40 ,0 , 2 * Math.PI);
ctx. stroke();
ctx. beginPath() ;
ctx. strokeStyle = "red";
ctx. lineWidth = 5;
ctx. arc(495, 265, 40 ,0 , 2 * Math.PI);
ctx. stroke();
ctx. beginPath() ;
ctx. strokeStyle = "yellow";
ctx. lineWidth = 5;
ctx. arc(360, 315, 40 ,0 , 2 * Math.PI);
ctx. stroke();
ctx. beginPath() ;
ctx. strokeStyle = "green";
ctx. lineWidth = 5;
ctx. arc(450, 315, 40 ,0 , 2 * Math.PI);
ctx. stroke();